// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"followingfeed/config"
	"followingfeed/internal/handler/article"
	"followingfeed/internal/handler/jwt"
	"followingfeed/internal/handler/user"
	"followingfeed/internal/repository"
	"followingfeed/internal/repository/cache"
	"followingfeed/internal/repository/dao"
	"followingfeed/internal/service"
	"followingfeed/ioc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp(cfg config.Config) (*App, error) {
	cmdable, err := ioc.InitRedis(cfg)
	if err != nil {
		return nil, err
	}
	jwtHandler := jwt.NewRedisJWTHandler(cmdable, cfg)
	loggerV1 := ioc.InitLogger(cfg)
	v := ioc.InitMiddlewares(cfg, cmdable, jwtHandler, loggerV1)
	db, err := ioc.InitMySQL(cfg)
	if err != nil {
		return nil, err
	}
	userDAO := dao.NewGORMUserDAO(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepositoryImpl(userDAO, userCache)
	userService := service.NewUserServiceImpl(userRepository)
	userHandler := user.NewUserHandler(userService, cmdable, loggerV1, jwtHandler)
	articleDAO := dao.NewGORMArticleDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := repository.NewArticleRepositoryImpl(articleDAO, articleCache, loggerV1)
	articleService := service.NewArticleServiceImpl(articleRepository)
	articleHandler := article.NewArticleHandler(articleService, loggerV1)
	engine := ioc.InitGin(v, userHandler, articleHandler, db, cmdable)
	app := &App{
		Server: engine,
	}
	return app, nil
}

// wire.go:

var thirdServiceSet = wire.NewSet(ioc.InitMySQL, ioc.InitRedis)

var userHandlerSet = wire.NewSet(cache.NewUserCache, dao.NewGORMUserDAO, repository.NewUserRepositoryImpl, service.NewUserServiceImpl, user.NewUserHandler)

var articleHandlerSet = wire.NewSet(dao.NewGORMArticleDAO, cache.NewRedisArticleCache, repository.NewArticleRepositoryImpl, service.NewArticleServiceImpl, article.NewArticleHandler)
