// Code generated by MockGen. DO NOT EDIT.
// Source: follow.go
//
// Generated by this command:
//
//	mockgen -source=follow.go -package=repomocks -destination=mocks/follow.mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	domain "followingfeed/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFollowRepository is a mock of FollowRepository interface.
type MockFollowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFollowRepositoryMockRecorder
	isgomock struct{}
}

// MockFollowRepositoryMockRecorder is the mock recorder for MockFollowRepository.
type MockFollowRepositoryMockRecorder struct {
	mock *MockFollowRepository
}

// NewMockFollowRepository creates a new mock instance.
func NewMockFollowRepository(ctrl *gomock.Controller) *MockFollowRepository {
	mock := &MockFollowRepository{ctrl: ctrl}
	mock.recorder = &MockFollowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowRepository) EXPECT() *MockFollowRepositoryMockRecorder {
	return m.recorder
}

// CountFollowers mocks base method.
func (m *MockFollowRepository) CountFollowers(ctx context.Context, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollowers", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollowers indicates an expected call of CountFollowers.
func (mr *MockFollowRepositoryMockRecorder) CountFollowers(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollowers", reflect.TypeOf((*MockFollowRepository)(nil).CountFollowers), ctx, uid)
}

// CountFollowing mocks base method.
func (m *MockFollowRepository) CountFollowing(ctx context.Context, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollowing", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollowing indicates an expected call of CountFollowing.
func (mr *MockFollowRepositoryMockRecorder) CountFollowing(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollowing", reflect.TypeOf((*MockFollowRepository)(nil).CountFollowing), ctx, uid)
}

// Follow mocks base method.
func (m *MockFollowRepository) Follow(ctx context.Context, uid, targetId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, uid, targetId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockFollowRepositoryMockRecorder) Follow(ctx, uid, targetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockFollowRepository)(nil).Follow), ctx, uid, targetId)
}

// IsFollowing mocks base method.
func (m *MockFollowRepository) IsFollowing(ctx context.Context, uid, targetId int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowing", ctx, uid, targetId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowing indicates an expected call of IsFollowing.
func (mr *MockFollowRepositoryMockRecorder) IsFollowing(ctx, uid, targetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowing", reflect.TypeOf((*MockFollowRepository)(nil).IsFollowing), ctx, uid, targetId)
}

// ListFollowersPage mocks base method.
func (m *MockFollowRepository) ListFollowersPage(ctx context.Context, uid int64, offset, limit int) ([]domain.Follow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowersPage", ctx, uid, offset, limit)
	ret0, _ := ret[0].([]domain.Follow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowersPage indicates an expected call of ListFollowersPage.
func (mr *MockFollowRepositoryMockRecorder) ListFollowersPage(ctx, uid, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowersPage", reflect.TypeOf((*MockFollowRepository)(nil).ListFollowersPage), ctx, uid, offset, limit)
}

// ListFollowingPage mocks base method.
func (m *MockFollowRepository) ListFollowingPage(ctx context.Context, uid int64, offset, limit int) ([]domain.Follow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowingPage", ctx, uid, offset, limit)
	ret0, _ := ret[0].([]domain.Follow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowingPage indicates an expected call of ListFollowingPage.
func (mr *MockFollowRepositoryMockRecorder) ListFollowingPage(ctx, uid, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowingPage", reflect.TypeOf((*MockFollowRepository)(nil).ListFollowingPage), ctx, uid, offset, limit)
}

// UnFollow mocks base method.
func (m *MockFollowRepository) UnFollow(ctx context.Context, uid, targetId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnFollow", ctx, uid, targetId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnFollow indicates an expected call of UnFollow.
func (mr *MockFollowRepositoryMockRecorder) UnFollow(ctx, uid, targetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnFollow", reflect.TypeOf((*MockFollowRepository)(nil).UnFollow), ctx, uid, targetId)
}
