// Code generated by MockGen. DO NOT EDIT.
// Source: interactive.go
//
// Generated by this command:
//
//	mockgen -source=interactive.go -package=repomocks -destination=mocks/interactive.mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	domain "followingfeed/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInteractiveRepository is a mock of InteractiveRepository interface.
type MockInteractiveRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInteractiveRepositoryMockRecorder
	isgomock struct{}
}

// MockInteractiveRepositoryMockRecorder is the mock recorder for MockInteractiveRepository.
type MockInteractiveRepositoryMockRecorder struct {
	mock *MockInteractiveRepository
}

// NewMockInteractiveRepository creates a new mock instance.
func NewMockInteractiveRepository(ctrl *gomock.Controller) *MockInteractiveRepository {
	mock := &MockInteractiveRepository{ctrl: ctrl}
	mock.recorder = &MockInteractiveRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractiveRepository) EXPECT() *MockInteractiveRepositoryMockRecorder {
	return m.recorder
}

// BatchGet mocks base method.
func (m *MockInteractiveRepository) BatchGet(ctx context.Context, biz string, bizIDs []int64) (map[int64]domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGet", ctx, biz, bizIDs)
	ret0, _ := ret[0].(map[int64]domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGet indicates an expected call of BatchGet.
func (mr *MockInteractiveRepositoryMockRecorder) BatchGet(ctx, biz, bizIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGet", reflect.TypeOf((*MockInteractiveRepository)(nil).BatchGet), ctx, biz, bizIDs)
}

// Collected mocks base method.
func (m *MockInteractiveRepository) Collected(ctx context.Context, biz string, bizID, uid int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collected", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Collected indicates an expected call of Collected.
func (mr *MockInteractiveRepositoryMockRecorder) Collected(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collected", reflect.TypeOf((*MockInteractiveRepository)(nil).Collected), ctx, biz, bizID, uid)
}

// CountCollected mocks base method.
func (m *MockInteractiveRepository) CountCollected(ctx context.Context, biz string, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCollected", ctx, biz, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCollected indicates an expected call of CountCollected.
func (mr *MockInteractiveRepositoryMockRecorder) CountCollected(ctx, biz, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCollected", reflect.TypeOf((*MockInteractiveRepository)(nil).CountCollected), ctx, biz, uid)
}

// DecrCollect mocks base method.
func (m *MockInteractiveRepository) DecrCollect(ctx context.Context, biz string, bizID, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrCollect", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrCollect indicates an expected call of DecrCollect.
func (mr *MockInteractiveRepositoryMockRecorder) DecrCollect(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrCollect", reflect.TypeOf((*MockInteractiveRepository)(nil).DecrCollect), ctx, biz, bizID, uid)
}

// DecrLike mocks base method.
func (m *MockInteractiveRepository) DecrLike(ctx context.Context, biz string, bizID, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrLike", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrLike indicates an expected call of DecrLike.
func (mr *MockInteractiveRepositoryMockRecorder) DecrLike(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrLike", reflect.TypeOf((*MockInteractiveRepository)(nil).DecrLike), ctx, biz, bizID, uid)
}

// Get mocks base method.
func (m *MockInteractiveRepository) Get(ctx context.Context, biz string, bizID int64) (domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, biz, bizID)
	ret0, _ := ret[0].(domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInteractiveRepositoryMockRecorder) Get(ctx, biz, bizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInteractiveRepository)(nil).Get), ctx, biz, bizID)
}

// GetArticleStatsByAuthor mocks base method.
func (m *MockInteractiveRepository) GetArticleStatsByAuthor(ctx context.Context, biz string, authorID int64) (domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleStatsByAuthor", ctx, biz, authorID)
	ret0, _ := ret[0].(domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleStatsByAuthor indicates an expected call of GetArticleStatsByAuthor.
func (mr *MockInteractiveRepositoryMockRecorder) GetArticleStatsByAuthor(ctx, biz, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleStatsByAuthor", reflect.TypeOf((*MockInteractiveRepository)(nil).GetArticleStatsByAuthor), ctx, biz, authorID)
}

// IncrCollect mocks base method.
func (m *MockInteractiveRepository) IncrCollect(ctx context.Context, biz string, bizID, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrCollect", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrCollect indicates an expected call of IncrCollect.
func (mr *MockInteractiveRepositoryMockRecorder) IncrCollect(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrCollect", reflect.TypeOf((*MockInteractiveRepository)(nil).IncrCollect), ctx, biz, bizID, uid)
}

// IncrLike mocks base method.
func (m *MockInteractiveRepository) IncrLike(ctx context.Context, biz string, bizID, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrLike", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrLike indicates an expected call of IncrLike.
func (mr *MockInteractiveRepositoryMockRecorder) IncrLike(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrLike", reflect.TypeOf((*MockInteractiveRepository)(nil).IncrLike), ctx, biz, bizID, uid)
}

// IncrRead mocks base method.
func (m *MockInteractiveRepository) IncrRead(ctx context.Context, biz string, bizID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrRead", ctx, biz, bizID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrRead indicates an expected call of IncrRead.
func (mr *MockInteractiveRepositoryMockRecorder) IncrRead(ctx, biz, bizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrRead", reflect.TypeOf((*MockInteractiveRepository)(nil).IncrRead), ctx, biz, bizID)
}

// Liked mocks base method.
func (m *MockInteractiveRepository) Liked(ctx context.Context, biz string, bizID, uid int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Liked", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Liked indicates an expected call of Liked.
func (mr *MockInteractiveRepositoryMockRecorder) Liked(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Liked", reflect.TypeOf((*MockInteractiveRepository)(nil).Liked), ctx, biz, bizID, uid)
}

// ListCollected mocks base method.
func (m *MockInteractiveRepository) ListCollected(ctx context.Context, biz string, uid int64, offset, limit int) ([]domain.PublishArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollected", ctx, biz, uid, offset, limit)
	ret0, _ := ret[0].([]domain.PublishArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollected indicates an expected call of ListCollected.
func (mr *MockInteractiveRepositoryMockRecorder) ListCollected(ctx, biz, uid, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollected", reflect.TypeOf((*MockInteractiveRepository)(nil).ListCollected), ctx, biz, uid, offset, limit)
}
