// Code generated by MockGen. DO NOT EDIT.
// Source: follow.go
//
// Generated by this command:
//
//	mockgen -source=follow.go -package=svcmocks -destination=mocks/follow.mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	domain "followingfeed/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFollowService is a mock of FollowService interface.
type MockFollowService struct {
	ctrl     *gomock.Controller
	recorder *MockFollowServiceMockRecorder
	isgomock struct{}
}

// MockFollowServiceMockRecorder is the mock recorder for MockFollowService.
type MockFollowServiceMockRecorder struct {
	mock *MockFollowService
}

// NewMockFollowService creates a new mock instance.
func NewMockFollowService(ctrl *gomock.Controller) *MockFollowService {
	mock := &MockFollowService{ctrl: ctrl}
	mock.recorder = &MockFollowServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowService) EXPECT() *MockFollowServiceMockRecorder {
	return m.recorder
}

// CountFollowers mocks base method.
func (m *MockFollowService) CountFollowers(ctx context.Context, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollowers", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollowers indicates an expected call of CountFollowers.
func (mr *MockFollowServiceMockRecorder) CountFollowers(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollowers", reflect.TypeOf((*MockFollowService)(nil).CountFollowers), ctx, uid)
}

// CountFollowing mocks base method.
func (m *MockFollowService) CountFollowing(ctx context.Context, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollowing", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollowing indicates an expected call of CountFollowing.
func (mr *MockFollowServiceMockRecorder) CountFollowing(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollowing", reflect.TypeOf((*MockFollowService)(nil).CountFollowing), ctx, uid)
}

// Follow mocks base method.
func (m *MockFollowService) Follow(ctx context.Context, uid, targetId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, uid, targetId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockFollowServiceMockRecorder) Follow(ctx, uid, targetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockFollowService)(nil).Follow), ctx, uid, targetId)
}

// IsFollowing mocks base method.
func (m *MockFollowService) IsFollowing(ctx context.Context, uid, targetId int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowing", ctx, uid, targetId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowing indicates an expected call of IsFollowing.
func (mr *MockFollowServiceMockRecorder) IsFollowing(ctx, uid, targetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowing", reflect.TypeOf((*MockFollowService)(nil).IsFollowing), ctx, uid, targetId)
}

// ListFollowersPage mocks base method.
func (m *MockFollowService) ListFollowersPage(ctx context.Context, uid int64, offset, limit int) ([]domain.Follow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowersPage", ctx, uid, offset, limit)
	ret0, _ := ret[0].([]domain.Follow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowersPage indicates an expected call of ListFollowersPage.
func (mr *MockFollowServiceMockRecorder) ListFollowersPage(ctx, uid, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowersPage", reflect.TypeOf((*MockFollowService)(nil).ListFollowersPage), ctx, uid, offset, limit)
}

// ListFollowingPage mocks base method.
func (m *MockFollowService) ListFollowingPage(ctx context.Context, uid int64, offset, limit int) ([]domain.Follow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowingPage", ctx, uid, offset, limit)
	ret0, _ := ret[0].([]domain.Follow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowingPage indicates an expected call of ListFollowingPage.
func (mr *MockFollowServiceMockRecorder) ListFollowingPage(ctx, uid, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowingPage", reflect.TypeOf((*MockFollowService)(nil).ListFollowingPage), ctx, uid, offset, limit)
}

// UnFollow mocks base method.
func (m *MockFollowService) UnFollow(ctx context.Context, uid, targetId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnFollow", ctx, uid, targetId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnFollow indicates an expected call of UnFollow.
func (mr *MockFollowServiceMockRecorder) UnFollow(ctx, uid, targetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnFollow", reflect.TypeOf((*MockFollowService)(nil).UnFollow), ctx, uid, targetId)
}
