// Code generated by MockGen. DO NOT EDIT.
// Source: interactive.go
//
// Generated by this command:
//
//	mockgen -source=interactive.go -package=svcmocks -destination=mocks/interactive.mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	domain "followingfeed/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInteractiveService is a mock of InteractiveService interface.
type MockInteractiveService struct {
	ctrl     *gomock.Controller
	recorder *MockInteractiveServiceMockRecorder
	isgomock struct{}
}

// MockInteractiveServiceMockRecorder is the mock recorder for MockInteractiveService.
type MockInteractiveServiceMockRecorder struct {
	mock *MockInteractiveService
}

// NewMockInteractiveService creates a new mock instance.
func NewMockInteractiveService(ctrl *gomock.Controller) *MockInteractiveService {
	mock := &MockInteractiveService{ctrl: ctrl}
	mock.recorder = &MockInteractiveServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractiveService) EXPECT() *MockInteractiveServiceMockRecorder {
	return m.recorder
}

// BatchGet mocks base method.
func (m *MockInteractiveService) BatchGet(ctx context.Context, biz string, bizIDs []int64) (map[int64]domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGet", ctx, biz, bizIDs)
	ret0, _ := ret[0].(map[int64]domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGet indicates an expected call of BatchGet.
func (mr *MockInteractiveServiceMockRecorder) BatchGet(ctx, biz, bizIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGet", reflect.TypeOf((*MockInteractiveService)(nil).BatchGet), ctx, biz, bizIDs)
}

// CancelCollect mocks base method.
func (m *MockInteractiveService) CancelCollect(ctx context.Context, biz string, bizID, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelCollect", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelCollect indicates an expected call of CancelCollect.
func (mr *MockInteractiveServiceMockRecorder) CancelCollect(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelCollect", reflect.TypeOf((*MockInteractiveService)(nil).CancelCollect), ctx, biz, bizID, uid)
}

// CancelLike mocks base method.
func (m *MockInteractiveService) CancelLike(ctx context.Context, biz string, bizID, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelLike", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelLike indicates an expected call of CancelLike.
func (mr *MockInteractiveServiceMockRecorder) CancelLike(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelLike", reflect.TypeOf((*MockInteractiveService)(nil).CancelLike), ctx, biz, bizID, uid)
}

// Collect mocks base method.
func (m *MockInteractiveService) Collect(ctx context.Context, biz string, bizID, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Collect indicates an expected call of Collect.
func (mr *MockInteractiveServiceMockRecorder) Collect(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockInteractiveService)(nil).Collect), ctx, biz, bizID, uid)
}

// CountCollected mocks base method.
func (m *MockInteractiveService) CountCollected(ctx context.Context, biz string, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCollected", ctx, biz, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCollected indicates an expected call of CountCollected.
func (mr *MockInteractiveServiceMockRecorder) CountCollected(ctx, biz, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCollected", reflect.TypeOf((*MockInteractiveService)(nil).CountCollected), ctx, biz, uid)
}

// Get mocks base method.
func (m *MockInteractiveService) Get(ctx context.Context, biz string, bizID, uid int64) (domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInteractiveServiceMockRecorder) Get(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInteractiveService)(nil).Get), ctx, biz, bizID, uid)
}

// GetArticleStatsByAuthor mocks base method.
func (m *MockInteractiveService) GetArticleStatsByAuthor(ctx context.Context, biz string, authorID int64) (domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleStatsByAuthor", ctx, biz, authorID)
	ret0, _ := ret[0].(domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleStatsByAuthor indicates an expected call of GetArticleStatsByAuthor.
func (mr *MockInteractiveServiceMockRecorder) GetArticleStatsByAuthor(ctx, biz, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleStatsByAuthor", reflect.TypeOf((*MockInteractiveService)(nil).GetArticleStatsByAuthor), ctx, biz, authorID)
}

// Like mocks base method.
func (m *MockInteractiveService) Like(ctx context.Context, biz string, bizID, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockInteractiveServiceMockRecorder) Like(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockInteractiveService)(nil).Like), ctx, biz, bizID, uid)
}

// ListCollected mocks base method.
func (m *MockInteractiveService) ListCollected(ctx context.Context, biz string, uid int64, offset, limit int) ([]domain.PublishArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollected", ctx, biz, uid, offset, limit)
	ret0, _ := ret[0].([]domain.PublishArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollected indicates an expected call of ListCollected.
func (mr *MockInteractiveServiceMockRecorder) ListCollected(ctx, biz, uid, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollected", reflect.TypeOf((*MockInteractiveService)(nil).ListCollected), ctx, biz, uid, offset, limit)
}

// RecordRead mocks base method.
func (m *MockInteractiveService) RecordRead(ctx context.Context, biz string, bizID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRead", ctx, biz, bizID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordRead indicates an expected call of RecordRead.
func (mr *MockInteractiveServiceMockRecorder) RecordRead(ctx, biz, bizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRead", reflect.TypeOf((*MockInteractiveService)(nil).RecordRead), ctx, biz, bizID)
}
