// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/my_profile.go
//
// Generated by this command:
//
//	mockgen -source=../../service/my_profile.go -package=svcmocks -destination=../../service/mocks/my_profile.mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	service "followingfeed/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMyProfileService is a mock of MyProfileService interface.
type MockMyProfileService struct {
	ctrl     *gomock.Controller
	recorder *MockMyProfileServiceMockRecorder
	isgomock struct{}
}

// MockMyProfileServiceMockRecorder is the mock recorder for MockMyProfileService.
type MockMyProfileServiceMockRecorder struct {
	mock *MockMyProfileService
}

// NewMockMyProfileService creates a new mock instance.
func NewMockMyProfileService(ctrl *gomock.Controller) *MockMyProfileService {
	mock := &MockMyProfileService{ctrl: ctrl}
	mock.recorder = &MockMyProfileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMyProfileService) EXPECT() *MockMyProfileServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMyProfileService) Get(ctx context.Context, uid int64) (service.MyProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uid)
	ret0, _ := ret[0].(service.MyProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMyProfileServiceMockRecorder) Get(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMyProfileService)(nil).Get), ctx, uid)
}
