// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/public_profile.go
//
// Generated by this command:
//
//	mockgen -source=../../service/public_profile.go -package=svcmocks -destination=../../service/mocks/public_profile.mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	service "followingfeed/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPublicProfileService is a mock of PublicProfileService interface.
type MockPublicProfileService struct {
	ctrl     *gomock.Controller
	recorder *MockPublicProfileServiceMockRecorder
	isgomock struct{}
}

// MockPublicProfileServiceMockRecorder is the mock recorder for MockPublicProfileService.
type MockPublicProfileServiceMockRecorder struct {
	mock *MockPublicProfileService
}

// NewMockPublicProfileService creates a new mock instance.
func NewMockPublicProfileService(ctrl *gomock.Controller) *MockPublicProfileService {
	mock := &MockPublicProfileService{ctrl: ctrl}
	mock.recorder = &MockPublicProfileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicProfileService) EXPECT() *MockPublicProfileServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPublicProfileService) Get(ctx context.Context, uid int64) (service.PublicProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uid)
	ret0, _ := ret[0].(service.PublicProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPublicProfileServiceMockRecorder) Get(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPublicProfileService)(nil).Get), ctx, uid)
}
