// Code generated by MockGen. DO NOT EDIT.
// Source: follow.go
//
// Generated by this command:
//
//	mockgen -source=follow.go -package=daomocks -destination=mocks/follow.mock.go
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	dao "followingfeed/internal/repository/dao"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFollowDAO is a mock of FollowDAO interface.
type MockFollowDAO struct {
	ctrl     *gomock.Controller
	recorder *MockFollowDAOMockRecorder
	isgomock struct{}
}

// MockFollowDAOMockRecorder is the mock recorder for MockFollowDAO.
type MockFollowDAOMockRecorder struct {
	mock *MockFollowDAO
}

// NewMockFollowDAO creates a new mock instance.
func NewMockFollowDAO(ctrl *gomock.Controller) *MockFollowDAO {
	mock := &MockFollowDAO{ctrl: ctrl}
	mock.recorder = &MockFollowDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowDAO) EXPECT() *MockFollowDAOMockRecorder {
	return m.recorder
}

// CountFollowers mocks base method.
func (m *MockFollowDAO) CountFollowers(ctx context.Context, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollowers", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollowers indicates an expected call of CountFollowers.
func (mr *MockFollowDAOMockRecorder) CountFollowers(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollowers", reflect.TypeOf((*MockFollowDAO)(nil).CountFollowers), ctx, uid)
}

// CountFollowing mocks base method.
func (m *MockFollowDAO) CountFollowing(ctx context.Context, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollowing", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollowing indicates an expected call of CountFollowing.
func (mr *MockFollowDAOMockRecorder) CountFollowing(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollowing", reflect.TypeOf((*MockFollowDAO)(nil).CountFollowing), ctx, uid)
}

// Insert mocks base method.
func (m *MockFollowDAO) Insert(ctx context.Context, uid, targetId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, uid, targetId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockFollowDAOMockRecorder) Insert(ctx, uid, targetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockFollowDAO)(nil).Insert), ctx, uid, targetId)
}

// IsFollowing mocks base method.
func (m *MockFollowDAO) IsFollowing(ctx context.Context, uid, targetId int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowing", ctx, uid, targetId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowing indicates an expected call of IsFollowing.
func (mr *MockFollowDAOMockRecorder) IsFollowing(ctx, uid, targetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowing", reflect.TypeOf((*MockFollowDAO)(nil).IsFollowing), ctx, uid, targetId)
}

// ListFollowersPage mocks base method.
func (m *MockFollowDAO) ListFollowersPage(ctx context.Context, uid int64, offset, limit int) ([]dao.Follow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowersPage", ctx, uid, offset, limit)
	ret0, _ := ret[0].([]dao.Follow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowersPage indicates an expected call of ListFollowersPage.
func (mr *MockFollowDAOMockRecorder) ListFollowersPage(ctx, uid, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowersPage", reflect.TypeOf((*MockFollowDAO)(nil).ListFollowersPage), ctx, uid, offset, limit)
}

// ListFollowingPage mocks base method.
func (m *MockFollowDAO) ListFollowingPage(ctx context.Context, uid int64, offset, limit int) ([]dao.Follow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowingPage", ctx, uid, offset, limit)
	ret0, _ := ret[0].([]dao.Follow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowingPage indicates an expected call of ListFollowingPage.
func (mr *MockFollowDAOMockRecorder) ListFollowingPage(ctx, uid, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowingPage", reflect.TypeOf((*MockFollowDAO)(nil).ListFollowingPage), ctx, uid, offset, limit)
}

// UnFollow mocks base method.
func (m *MockFollowDAO) UnFollow(ctx context.Context, uid, targetId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnFollow", ctx, uid, targetId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnFollow indicates an expected call of UnFollow.
func (mr *MockFollowDAOMockRecorder) UnFollow(ctx, uid, targetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnFollow", reflect.TypeOf((*MockFollowDAO)(nil).UnFollow), ctx, uid, targetId)
}
