// Code generated by MockGen. DO NOT EDIT.
// Source: dao/interactive.go
//
// Generated by this command:
//
//	mockgen -source=dao/interactive.go -package=daomocks -destination=dao/mocks/interactive.mock.go
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	dao "followingfeed/internal/repository/dao"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInteractiveDAO is a mock of InteractiveDAO interface.
type MockInteractiveDAO struct {
	ctrl     *gomock.Controller
	recorder *MockInteractiveDAOMockRecorder
	isgomock struct{}
}

// MockInteractiveDAOMockRecorder is the mock recorder for MockInteractiveDAO.
type MockInteractiveDAOMockRecorder struct {
	mock *MockInteractiveDAO
}

// NewMockInteractiveDAO creates a new mock instance.
func NewMockInteractiveDAO(ctrl *gomock.Controller) *MockInteractiveDAO {
	mock := &MockInteractiveDAO{ctrl: ctrl}
	mock.recorder = &MockInteractiveDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractiveDAO) EXPECT() *MockInteractiveDAOMockRecorder {
	return m.recorder
}

// BatchGet mocks base method.
func (m *MockInteractiveDAO) BatchGet(ctx context.Context, biz string, bizIDs []int64) ([]dao.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGet", ctx, biz, bizIDs)
	ret0, _ := ret[0].([]dao.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGet indicates an expected call of BatchGet.
func (mr *MockInteractiveDAOMockRecorder) BatchGet(ctx, biz, bizIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGet", reflect.TypeOf((*MockInteractiveDAO)(nil).BatchGet), ctx, biz, bizIDs)
}

// Collected mocks base method.
func (m *MockInteractiveDAO) Collected(ctx context.Context, biz string, bizID, uid int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collected", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Collected indicates an expected call of Collected.
func (mr *MockInteractiveDAOMockRecorder) Collected(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collected", reflect.TypeOf((*MockInteractiveDAO)(nil).Collected), ctx, biz, bizID, uid)
}

// CountCollected mocks base method.
func (m *MockInteractiveDAO) CountCollected(ctx context.Context, biz string, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCollected", ctx, biz, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCollected indicates an expected call of CountCollected.
func (mr *MockInteractiveDAOMockRecorder) CountCollected(ctx, biz, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCollected", reflect.TypeOf((*MockInteractiveDAO)(nil).CountCollected), ctx, biz, uid)
}

// DeleteCollectInfo mocks base method.
func (m *MockInteractiveDAO) DeleteCollectInfo(ctx context.Context, biz string, bizID, uid int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollectInfo", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCollectInfo indicates an expected call of DeleteCollectInfo.
func (mr *MockInteractiveDAOMockRecorder) DeleteCollectInfo(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollectInfo", reflect.TypeOf((*MockInteractiveDAO)(nil).DeleteCollectInfo), ctx, biz, bizID, uid)
}

// DeleteLikeInfo mocks base method.
func (m *MockInteractiveDAO) DeleteLikeInfo(ctx context.Context, biz string, bizID, uid int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLikeInfo", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLikeInfo indicates an expected call of DeleteLikeInfo.
func (mr *MockInteractiveDAOMockRecorder) DeleteLikeInfo(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLikeInfo", reflect.TypeOf((*MockInteractiveDAO)(nil).DeleteLikeInfo), ctx, biz, bizID, uid)
}

// Get mocks base method.
func (m *MockInteractiveDAO) Get(ctx context.Context, biz string, bizID int64) (dao.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, biz, bizID)
	ret0, _ := ret[0].(dao.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInteractiveDAOMockRecorder) Get(ctx, biz, bizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInteractiveDAO)(nil).Get), ctx, biz, bizID)
}

// GetArticleStatsByAuthor mocks base method.
func (m *MockInteractiveDAO) GetArticleStatsByAuthor(ctx context.Context, biz string, authorID int64) (dao.ArticleStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleStatsByAuthor", ctx, biz, authorID)
	ret0, _ := ret[0].(dao.ArticleStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleStatsByAuthor indicates an expected call of GetArticleStatsByAuthor.
func (mr *MockInteractiveDAOMockRecorder) GetArticleStatsByAuthor(ctx, biz, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleStatsByAuthor", reflect.TypeOf((*MockInteractiveDAO)(nil).GetArticleStatsByAuthor), ctx, biz, authorID)
}

// IncrRead mocks base method.
func (m *MockInteractiveDAO) IncrRead(ctx context.Context, biz string, bizID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrRead", ctx, biz, bizID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrRead indicates an expected call of IncrRead.
func (mr *MockInteractiveDAOMockRecorder) IncrRead(ctx, biz, bizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrRead", reflect.TypeOf((*MockInteractiveDAO)(nil).IncrRead), ctx, biz, bizID)
}

// InsertCollectInfo mocks base method.
func (m *MockInteractiveDAO) InsertCollectInfo(ctx context.Context, biz string, bizID, uid int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCollectInfo", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCollectInfo indicates an expected call of InsertCollectInfo.
func (mr *MockInteractiveDAOMockRecorder) InsertCollectInfo(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCollectInfo", reflect.TypeOf((*MockInteractiveDAO)(nil).InsertCollectInfo), ctx, biz, bizID, uid)
}

// InsertLikeInfo mocks base method.
func (m *MockInteractiveDAO) InsertLikeInfo(ctx context.Context, biz string, bizID, uid int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLikeInfo", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertLikeInfo indicates an expected call of InsertLikeInfo.
func (mr *MockInteractiveDAOMockRecorder) InsertLikeInfo(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLikeInfo", reflect.TypeOf((*MockInteractiveDAO)(nil).InsertLikeInfo), ctx, biz, bizID, uid)
}

// Liked mocks base method.
func (m *MockInteractiveDAO) Liked(ctx context.Context, biz string, bizID, uid int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Liked", ctx, biz, bizID, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Liked indicates an expected call of Liked.
func (mr *MockInteractiveDAOMockRecorder) Liked(ctx, biz, bizID, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Liked", reflect.TypeOf((*MockInteractiveDAO)(nil).Liked), ctx, biz, bizID, uid)
}

// ListCollected mocks base method.
func (m *MockInteractiveDAO) ListCollected(ctx context.Context, biz string, uid int64, offset, limit int) ([]dao.PublishArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollected", ctx, biz, uid, offset, limit)
	ret0, _ := ret[0].([]dao.PublishArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollected indicates an expected call of ListCollected.
func (mr *MockInteractiveDAOMockRecorder) ListCollected(ctx, biz, uid, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollected", reflect.TypeOf((*MockInteractiveDAO)(nil).ListCollected), ctx, biz, uid, offset, limit)
}
