// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/jwt/types.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/jwt/types.go -package=jwtmocks -destination=internal/handler/jwt/mocks/jwt.mock.go
//

// Package jwtmocks is a generated GoMock package.
package jwtmocks

import (
	jwt "followingfeed/internal/handler/jwt"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockJWTHandler is a mock of JWTHandler interface.
type MockJWTHandler struct {
	ctrl     *gomock.Controller
	recorder *MockJWTHandlerMockRecorder
	isgomock struct{}
}

// MockJWTHandlerMockRecorder is the mock recorder for MockJWTHandler.
type MockJWTHandlerMockRecorder struct {
	mock *MockJWTHandler
}

// NewMockJWTHandler creates a new mock instance.
func NewMockJWTHandler(ctrl *gomock.Controller) *MockJWTHandler {
	mock := &MockJWTHandler{ctrl: ctrl}
	mock.recorder = &MockJWTHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTHandler) EXPECT() *MockJWTHandlerMockRecorder {
	return m.recorder
}

// CheckSession mocks base method.
func (m *MockJWTHandler) CheckSession(ctx *gin.Context, Ssid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSession", ctx, Ssid)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckSession indicates an expected call of CheckSession.
func (mr *MockJWTHandlerMockRecorder) CheckSession(ctx, Ssid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSession", reflect.TypeOf((*MockJWTHandler)(nil).CheckSession), ctx, Ssid)
}

// ClearToken mocks base method.
func (m *MockJWTHandler) ClearToken(ctx *gin.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearToken", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearToken indicates an expected call of ClearToken.
func (mr *MockJWTHandlerMockRecorder) ClearToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearToken", reflect.TypeOf((*MockJWTHandler)(nil).ClearToken), ctx)
}

// ExtractToken mocks base method.
func (m *MockJWTHandler) ExtractToken(ctx *gin.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractToken", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExtractToken indicates an expected call of ExtractToken.
func (mr *MockJWTHandlerMockRecorder) ExtractToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractToken", reflect.TypeOf((*MockJWTHandler)(nil).ExtractToken), ctx)
}

// ParseAccessToken mocks base method.
func (m *MockJWTHandler) ParseAccessToken(token string) (*jwt.UserClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccessToken", token)
	ret0, _ := ret[0].(*jwt.UserClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccessToken indicates an expected call of ParseAccessToken.
func (mr *MockJWTHandlerMockRecorder) ParseAccessToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccessToken", reflect.TypeOf((*MockJWTHandler)(nil).ParseAccessToken), token)
}

// ParseRefreshToken mocks base method.
func (m *MockJWTHandler) ParseRefreshToken(token string) (*jwt.RefreshClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRefreshToken", token)
	ret0, _ := ret[0].(*jwt.RefreshClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRefreshToken indicates an expected call of ParseRefreshToken.
func (mr *MockJWTHandlerMockRecorder) ParseRefreshToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRefreshToken", reflect.TypeOf((*MockJWTHandler)(nil).ParseRefreshToken), token)
}

// SetJWTToken mocks base method.
func (m *MockJWTHandler) SetJWTToken(ctx *gin.Context, uid int64, Ssid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJWTToken", ctx, uid, Ssid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJWTToken indicates an expected call of SetJWTToken.
func (mr *MockJWTHandlerMockRecorder) SetJWTToken(ctx, uid, Ssid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJWTToken", reflect.TypeOf((*MockJWTHandler)(nil).SetJWTToken), ctx, uid, Ssid)
}

// SetLoginToken mocks base method.
func (m *MockJWTHandler) SetLoginToken(ctx *gin.Context, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLoginToken", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLoginToken indicates an expected call of SetLoginToken.
func (mr *MockJWTHandlerMockRecorder) SetLoginToken(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLoginToken", reflect.TypeOf((*MockJWTHandler)(nil).SetLoginToken), ctx, uid)
}
