// Code generated by MockGen. DO NOT EDIT.
// Source: cache/article.go
//
// Generated by this command:
//
//	mockgen -source=cache/article.go -package=cachemocks -destination=cache/mocks/article.mock.go
//

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	domain "followingfeed/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockArticleCache is a mock of ArticleCache interface.
type MockArticleCache struct {
	ctrl     *gomock.Controller
	recorder *MockArticleCacheMockRecorder
	isgomock struct{}
}

// MockArticleCacheMockRecorder is the mock recorder for MockArticleCache.
type MockArticleCacheMockRecorder struct {
	mock *MockArticleCache
}

// NewMockArticleCache creates a new mock instance.
func NewMockArticleCache(ctrl *gomock.Controller) *MockArticleCache {
	mock := &MockArticleCache{ctrl: ctrl}
	mock.recorder = &MockArticleCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleCache) EXPECT() *MockArticleCacheMockRecorder {
	return m.recorder
}

// DelFirstPage mocks base method.
func (m *MockArticleCache) DelFirstPage(ctx context.Context, authorId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelFirstPage", ctx, authorId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelFirstPage indicates an expected call of DelFirstPage.
func (mr *MockArticleCacheMockRecorder) DelFirstPage(ctx, authorId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelFirstPage", reflect.TypeOf((*MockArticleCache)(nil).DelFirstPage), ctx, authorId)
}

// DelPublished mocks base method.
func (m *MockArticleCache) DelPublished(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelPublished", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelPublished indicates an expected call of DelPublished.
func (mr *MockArticleCacheMockRecorder) DelPublished(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelPublished", reflect.TypeOf((*MockArticleCache)(nil).DelPublished), ctx)
}

// GetFirstPage mocks base method.
func (m *MockArticleCache) GetFirstPage(ctx context.Context, authorId int64) ([]domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstPage", ctx, authorId)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstPage indicates an expected call of GetFirstPage.
func (mr *MockArticleCacheMockRecorder) GetFirstPage(ctx, authorId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstPage", reflect.TypeOf((*MockArticleCache)(nil).GetFirstPage), ctx, authorId)
}

// GetPublishedCount mocks base method.
func (m *MockArticleCache) GetPublishedCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishedCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublishedCount indicates an expected call of GetPublishedCount.
func (mr *MockArticleCacheMockRecorder) GetPublishedCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishedCount", reflect.TypeOf((*MockArticleCache)(nil).GetPublishedCount), ctx)
}

// GetPublishedFirstPage mocks base method.
func (m *MockArticleCache) GetPublishedFirstPage(ctx context.Context) ([]domain.PublishArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishedFirstPage", ctx)
	ret0, _ := ret[0].([]domain.PublishArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublishedFirstPage indicates an expected call of GetPublishedFirstPage.
func (mr *MockArticleCacheMockRecorder) GetPublishedFirstPage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishedFirstPage", reflect.TypeOf((*MockArticleCache)(nil).GetPublishedFirstPage), ctx)
}

// SetFirstPage mocks base method.
func (m *MockArticleCache) SetFirstPage(ctx context.Context, authorId int64, articles []domain.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFirstPage", ctx, authorId, articles)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFirstPage indicates an expected call of SetFirstPage.
func (mr *MockArticleCacheMockRecorder) SetFirstPage(ctx, authorId, articles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFirstPage", reflect.TypeOf((*MockArticleCache)(nil).SetFirstPage), ctx, authorId, articles)
}

// SetPublishedCount mocks base method.
func (m *MockArticleCache) SetPublishedCount(ctx context.Context, count int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPublishedCount", ctx, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPublishedCount indicates an expected call of SetPublishedCount.
func (mr *MockArticleCacheMockRecorder) SetPublishedCount(ctx, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPublishedCount", reflect.TypeOf((*MockArticleCache)(nil).SetPublishedCount), ctx, count)
}

// SetPublishedFirstPage mocks base method.
func (m *MockArticleCache) SetPublishedFirstPage(ctx context.Context, articles []domain.PublishArticle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPublishedFirstPage", ctx, articles)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPublishedFirstPage indicates an expected call of SetPublishedFirstPage.
func (mr *MockArticleCacheMockRecorder) SetPublishedFirstPage(ctx, articles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPublishedFirstPage", reflect.TypeOf((*MockArticleCache)(nil).SetPublishedFirstPage), ctx, articles)
}
