// Code generated by MockGen. DO NOT EDIT.
// Source: user_profile.go
//
// Generated by this command:
//
//	mockgen -source=user_profile.go -package=cachemocks -destination=mocks/user_profile.mock.go
//

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	cache "followingfeed/internal/repository/cache"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPublicProfileCache is a mock of PublicProfileCache interface.
type MockPublicProfileCache struct {
	ctrl     *gomock.Controller
	recorder *MockPublicProfileCacheMockRecorder
	isgomock struct{}
}

// MockPublicProfileCacheMockRecorder is the mock recorder for MockPublicProfileCache.
type MockPublicProfileCacheMockRecorder struct {
	mock *MockPublicProfileCache
}

// NewMockPublicProfileCache creates a new mock instance.
func NewMockPublicProfileCache(ctrl *gomock.Controller) *MockPublicProfileCache {
	mock := &MockPublicProfileCache{ctrl: ctrl}
	mock.recorder = &MockPublicProfileCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicProfileCache) EXPECT() *MockPublicProfileCacheMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockPublicProfileCache) Del(ctx context.Context, uids ...int64) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range uids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockPublicProfileCacheMockRecorder) Del(ctx any, uids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, uids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockPublicProfileCache)(nil).Del), varargs...)
}

// Get mocks base method.
func (m *MockPublicProfileCache) Get(ctx context.Context, uid int64) (cache.PublicProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uid)
	ret0, _ := ret[0].(cache.PublicProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPublicProfileCacheMockRecorder) Get(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPublicProfileCache)(nil).Get), ctx, uid)
}

// Set mocks base method.
func (m *MockPublicProfileCache) Set(ctx context.Context, profile cache.PublicProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockPublicProfileCacheMockRecorder) Set(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockPublicProfileCache)(nil).Set), ctx, profile)
}

// SetNotFound mocks base method.
func (m *MockPublicProfileCache) SetNotFound(ctx context.Context, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNotFound", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNotFound indicates an expected call of SetNotFound.
func (mr *MockPublicProfileCacheMockRecorder) SetNotFound(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNotFound", reflect.TypeOf((*MockPublicProfileCache)(nil).SetNotFound), ctx, uid)
}

// MockUserArticleStatsCache is a mock of UserArticleStatsCache interface.
type MockUserArticleStatsCache struct {
	ctrl     *gomock.Controller
	recorder *MockUserArticleStatsCacheMockRecorder
	isgomock struct{}
}

// MockUserArticleStatsCacheMockRecorder is the mock recorder for MockUserArticleStatsCache.
type MockUserArticleStatsCacheMockRecorder struct {
	mock *MockUserArticleStatsCache
}

// NewMockUserArticleStatsCache creates a new mock instance.
func NewMockUserArticleStatsCache(ctrl *gomock.Controller) *MockUserArticleStatsCache {
	mock := &MockUserArticleStatsCache{ctrl: ctrl}
	mock.recorder = &MockUserArticleStatsCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserArticleStatsCache) EXPECT() *MockUserArticleStatsCacheMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockUserArticleStatsCache) Del(ctx context.Context, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockUserArticleStatsCacheMockRecorder) Del(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockUserArticleStatsCache)(nil).Del), ctx, uid)
}

// Get mocks base method.
func (m *MockUserArticleStatsCache) Get(ctx context.Context, uid int64) (cache.ArticleStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uid)
	ret0, _ := ret[0].(cache.ArticleStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserArticleStatsCacheMockRecorder) Get(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserArticleStatsCache)(nil).Get), ctx, uid)
}

// Set mocks base method.
func (m *MockUserArticleStatsCache) Set(ctx context.Context, uid int64, stats cache.ArticleStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, uid, stats)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockUserArticleStatsCacheMockRecorder) Set(ctx, uid, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockUserArticleStatsCache)(nil).Set), ctx, uid, stats)
}

// MockUserProfileCacheInvalidator is a mock of UserProfileCacheInvalidator interface.
type MockUserProfileCacheInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileCacheInvalidatorMockRecorder
	isgomock struct{}
}

// MockUserProfileCacheInvalidatorMockRecorder is the mock recorder for MockUserProfileCacheInvalidator.
type MockUserProfileCacheInvalidatorMockRecorder struct {
	mock *MockUserProfileCacheInvalidator
}

// NewMockUserProfileCacheInvalidator creates a new mock instance.
func NewMockUserProfileCacheInvalidator(ctrl *gomock.Controller) *MockUserProfileCacheInvalidator {
	mock := &MockUserProfileCacheInvalidator{ctrl: ctrl}
	mock.recorder = &MockUserProfileCacheInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileCacheInvalidator) EXPECT() *MockUserProfileCacheInvalidatorMockRecorder {
	return m.recorder
}

// DelArticleStats mocks base method.
func (m *MockUserProfileCacheInvalidator) DelArticleStats(ctx context.Context, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelArticleStats", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelArticleStats indicates an expected call of DelArticleStats.
func (mr *MockUserProfileCacheInvalidatorMockRecorder) DelArticleStats(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelArticleStats", reflect.TypeOf((*MockUserProfileCacheInvalidator)(nil).DelArticleStats), ctx, uid)
}

// DelPublicProfiles mocks base method.
func (m *MockUserProfileCacheInvalidator) DelPublicProfiles(ctx context.Context, uids ...int64) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range uids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DelPublicProfiles", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelPublicProfiles indicates an expected call of DelPublicProfiles.
func (mr *MockUserProfileCacheInvalidatorMockRecorder) DelPublicProfiles(ctx any, uids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, uids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelPublicProfiles", reflect.TypeOf((*MockUserProfileCacheInvalidator)(nil).DelPublicProfiles), varargs...)
}
